### ISSUE TITLE
Add support for llama_index to Portkey's SDK

### ISSUE THREAD

**Issue by rachittshah** [Portkey-AI/docs#1]
Description: The current implementation of the LlamaIndex function is not working properly when **kwargs is passed as an argument. Specifically, when using the function in combination with the openai-python library, **kwargs are getting dropped somewhere in the llama_index function.

Steps to reproduce:

Use the openai-python library to create an embedding object as follows:
```
completion = openai.Embedding.create(
    model="text-embedding-ada-002",
    input="sample",
    headers={
        "x-portkey-api-key": "x2trk",
        "x-portkey-mode": "proxy openai"
    },
    user="country_passages@rohit.portkey"
)
```

To-do:
- Call the LlamaIndex function with the embedding object and **kwargs as an argument.
- Check the output of the LlamaIndex function and compare it with the expected output.

Expected result:
The LlamaIndex function should use the **kwargs argument to correctly process the input and provide the expected output.

Actual result:
The LlamaIndex function is dropping the **kwargs argument, leading to unexpected behavior and incorrect output.

Proposed solution:
Update the LlamaIndex function to properly handle **kwargs arguments passed to it. This will ensure that the function can be used effectively with the openai-python library and other similar libraries.

**Comment by roh26it** [comment]
Thanks for creating this issue! 

I was also exploring ServiceContext in llamaindex which would allow us to send a custom embedding class. We should check that out as well.
