### ISSUE TITLE
Kebab-case for Feedback API

### ISSUE THREAD

**Issue by vrushankportkey** [Portkey-AI/docs#4]
https://github.com/Portkey-AI/docs/blob/main/feedback.md

![image](https://github.com/Portkey-AI/docs/assets/134934501/715e04fc-fefb-4b5f-a498-2aaad33a3a56)

Here we use trace_id while sending feedback. For consistency, we can have that as kebab case trace-id as well.

**Comment by roh26it** [comment]
@ayush-portkey - what do you think?
